description: "Home of Panda Robot's web novels, art, reviews and more"
remote_theme: jekyll/minima
future: true
paginate: 10
paginate_path: "/blog/page:num/"
comments: true
gem 'github-pages', '170', group: :jekyll_plugins
minima:
  skin: dark
  social_links:
    - { platform: royalroad, user_url: "https://www.royalroad.com/profile/358926" }
    - { platform: tapas, user_url: "https://tapas.io/pandarobot"}
    - { platform: tumblr-icon, user_url: "https://www.tumblr.com/pandarobotwastaken"}
header_pages:
  - _pages/BANANA_CIDER.md
  - _pages/ABOUT.md
include:
  - _pages
  - _resources
  - _layouts
  - _includes
  - _posts
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - simple-jekyll-search
  - jekyll-paginate
